// The setup wizard, from an appliance that has never been configured to one
// that serves a scan. Four things are proved here and nowhere else: that
// claiming the wizard takes it away from every other browser on the network,
// that "Test connection" tells an operator which of their three credentials
// is the broken one, that a generated SMTP password survives blank password
// submissions, and that the file it writes is a file the appliance actually
// runs on.
//
// One browser throughout. The wizard belongs to the browser that
// pressed Start until scan2graph is restarted, so a fresh context per test -
// Playwright's default, and a fresh cookie jar - would be locked out of the
// wizard this suite itself claimed.

import { createHash, randomUUID } from 'node:crypto';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { expect, test } from '@playwright/test';

import { serving as pollSmtp } from '../lib/appliance.mjs';
import { FIXTURE_SECRET, resetFakes } from '../lib/fakes.mjs';
import { signIn } from '../lib/sign-in.mjs';
import { makePdf, sendScan } from '../lib/smtp.mjs';

const e2e = path.join(path.dirname(fileURLToPath(import.meta.url)), '..');
const WIZARD = 'http://127.0.0.1:18082'; // playwright.config.mjs starts it there
const CONFIG = path.join(e2e, '.tmp', 'wizard', 'scan2graph.env');

// The wizard releases this port before the same process starts the appliance.
// Its callback URL is registered in e2e/fakes/main.go.
const APPLIANCE = WIZARD;
const SMTP_PORT = 12526;

// The form as an operator fills it in, pointed at the fakes. The two password
// boxes are kept apart from it, below, because one of them is deliberately
// typed wrong later on.
const FORM = {
  S2G_ENTRA_TENANT_ID: '00000000-0000-0000-0000-0000000000aa',
  S2G_ENTRA_CLIENT_ID: '00000000-0000-0000-0000-000000000001',
  S2G_GRAPH_SENDER: 'scanner@corp.example',
  S2G_ALLOWED_RECIPIENT_DOMAINS: 'corp.example',
  S2G_PUBLIC_BASE_URL: APPLIANCE,
  S2G_HTTP_ADDR: APPLIANCE.replace('http://', ''),
  S2G_SMTP_ADDR: `127.0.0.1:${SMTP_PORT}`,
  S2G_SMTP_USERNAME: 'printer',
  S2G_DI_ENDPOINT: 'https://127.0.0.1:19443',
};

// The client secret box never renders back. The SMTP password is generated by
// the wizard below, then deliberately left blank so the pending form has to
// retain it through every later submission.
const SECRETS = {
  S2G_ENTRA_CLIENT_SECRET: FIXTURE_SECRET,
};

const CHECKS = ['Entra sign-in', 'App-only token', 'Document Intelligence'];

test.describe.configure({ mode: 'serial' });

let page; // the browser that claims the wizard
let generatedSmtpPassword; // held only in memory; never written to test output

test.beforeAll(async ({ browser }) => {
  // delivery.spec.mjs leaves Document Intelligence in fail mode, and the OCR
  // at the end of this file would inherit it.
  await resetFakes();
  page = await browser.newPage();
});

test.afterAll(async () => {
  await page?.close();
});

test('the browser that claims the wizard is the only one that gets it', async ({ browser }) => {
  const other = await browser.newContext();
  const bystander = await other.newPage();

  // Both browsers see the door while nobody holds the key, so the 404s below
  // are evidence about the claim rather than about a wrong URL.
  await page.goto(WIZARD);
  await bystander.goto(WIZARD);
  await expect(bystander.getByRole('button', { name: 'Start configuration' })).toBeVisible();

  await page.getByRole('button', { name: 'Start configuration' }).click();
  await expect(page.getByRole('button', { name: 'Save and start' })).toBeVisible();

  expect((await bystander.goto(`${WIZARD}/setup`)).status()).toBe(404);

  await other.close();
});

test('advanced scanner settings stay folded but reopen around bad input', async () => {
  const profiles = page.locator('#S2G_PROFILES');
  const smtpBind = page.locator('#S2G_SMTP_ADDR');
  const httpBind = page.locator('#S2G_HTTP_ADDR');
  await expect(profiles).toBeHidden();
  await expect(smtpBind).toBeHidden();
  await expect(httpBind).toBeHidden();

  await revealField('S2G_PROFILES');
  await expect(profiles).toBeVisible();
  await expect(smtpBind).toBeVisible();
  await revealField('S2G_HTTP_ADDR');
  await expect(httpBind).toBeVisible();

  const webWithoutSender = page.getByLabel('Row 1: web');
  await webWithoutSender.check();
  await page.locator('details:has(#S2G_PROFILES) > summary').click();
  await testConnection().click();
  await expect(webWithoutSender).toBeVisible();
  await expect(webWithoutSender).toBeChecked();
  await expect(page.locator('.field.bad:has(#S2G_PROFILES)')).toContainText('needs the address');
  await webWithoutSender.uncheck();
});

test('generates an SMTP password for the pending configuration', async () => {
  await fillForm(FIXTURE_SECRET);
  await page.locator('button[name="action"][value="generate-smtp-password"]').click();
  generatedSmtpPassword = (await page.locator('code#generated-smtp-password').textContent())?.trim();
  if (!generatedSmtpPassword) throw new Error('the wizard did not reveal a generated SMTP password');
  await expect(page.locator('#S2G_SMTP_PASSWORD')).toHaveValue('');
});

test('Test connection passes against the fakes, and singles out a broken secret', async () => {
  await fillForm(FIXTURE_SECRET);
  await expect(page.locator('#S2G_SMTP_PASSWORD')).toHaveValue('');
  await testConnection().click();
  for (const name of CHECKS) await expect(result(name)).toHaveText(/\bok\b/i);
  await expect(page.locator('code#generated-smtp-password')).toHaveCount(0);

  // The whole reason the feature exists: with a secret Entra will not accept,
  // the sign-in check - which needs no secret - still passes, and the two
  // that do need one say what Entra said, in the operator's own words. The
  // fake answers with the sentence real Entra sends, so this asserts the
  // headline claim rather than oauth2's rendering of "invalid_client".
  await fillForm(`${FIXTURE_SECRET}-wrong`);
  await expect(page.locator('#S2G_SMTP_PASSWORD')).toHaveValue('');
  await testConnection().click();
  await expect(result('Entra sign-in')).toHaveText(/\bok\b/i);
  for (const name of ['App-only token', 'Document Intelligence']) {
    await expect(result(name)).not.toHaveText(/\bok\b/i);
    await expect(result(name)).toContainText('AADSTS7000215: Invalid client secret provided');
  }
});

test('Save and start serves a scan in the same process on the same HTTP port', async () => {
  await fillForm(FIXTURE_SECRET);
  await expect(page.locator('#S2G_SMTP_PASSWORD')).toHaveValue('');
  await page.getByRole('button', { name: 'Save and start' }).click();
  await expect(page.getByRole('heading', { name: 'Starting scan2graph' })).toBeVisible();
  await expect(page.locator('head style')).toHaveCount(1);
  await expect(page.locator('link[rel="stylesheet"]')).toHaveCount(0);
  await expect(page.locator('body')).toHaveCSS('margin-top', '0px');
  // The path it wrote, and - because this run configured a public URL - the
  // redirect URI the app registration needs, which is the last chance to say
  // so before the wizard disappears.
  await expect(page.locator('p code')).toHaveText(CONFIG);
  await expect(page.locator('.guide code')).toHaveText(`${APPLIANCE}/auth/callback`);

  await expect(page.getByRole('link', { name: 'Open scan2graph' })).toHaveAttribute('href', APPLIANCE);
  await expect(page.locator('body')).toContainText('does not confirm that startup succeeded');
  await expect(page.locator('code#generated-smtp-password')).toHaveCount(0);
  await serving();
  // The holder's old cookie grants no setup routes after handover.
  expect((await page.request.get(`${APPLIANCE}/setup`)).status()).toBe(404);
  expect((await page.request.post(`${APPLIANCE}/setup`)).status()).toBe(404);
  expect((await page.request.post(`${APPLIANCE}/setup/start`)).status()).toBe(404);

  const subject = `e2e setup ${randomUUID().slice(0, 8)}`;
  const pdf = makePdf(subject);
  const codes = await sendScan({
    from: 'printer@scanner.local',
    to: 'alice@corp.example',
    subject,
    pdf,
    password: generatedSmtpPassword,
    port: SMTP_PORT,
  });
  expect(codes.body).toBe(250);

  await signIn(page, 'alice', APPLIANCE);
  const row = page.locator('tr').filter({ hasText: subject });
  await expect(async () => {
    await page.reload();
    // textContent, not innerText: the stylesheet capitalizes the status.
    await expect(row.locator('.status')).toHaveText('ready');
  }).toPass({ intervals: [50], timeout: 30_000 });

  await row.getByRole('link').click();
  const [download] = await Promise.all([
    page.waitForEvent('download'),
    page.locator('a.download').click(),
  ]);
  const chunks = [];
  for await (const chunk of await download.createReadStream()) chunks.push(chunk);
  // Searchable, and made so from this scan: the SMTP port, the Entra app
  // registration and the Document Intelligence endpoint in that file were all
  // used to get here.
  expect(Buffer.concat(chunks).toString())
    .toContain(`OCRED-BY-FAKE ${createHash('sha256').update(pdf).digest('hex')}`);
});

// The button by the name and value the wizard's form gives it - its label is
// the other half of the interface and not this test's to fix.
const testConnection = () => page.locator('button[name="action"][value="test"]');

// One check's result: the block above the form is a list, one entry per named
// check.
const result = (name) => page.locator('li').filter({ hasText: name });

// fillForm types the non-SMTP form and the Entra secret. Every submission
// re-renders the form and empties the password boxes, so each step fills the
// visible values from scratch while the pending form retains the generated
// SMTP password.
async function fillForm(entraSecret) {
  const boxes = { ...FORM, ...SECRETS, S2G_ENTRA_CLIENT_SECRET: entraSecret };
  for (const [name, value] of Object.entries(boxes)) {
    await revealField(name);
    await page.locator(`#${name}`).fill(value);
  }
}

// A group can put several fields in one disclosure. Once the first field has
// opened it, the next one is already visible and must not click it closed.
async function revealField(name) {
  const field = page.locator(`#${name}`);
  if (await field.isVisible()) return;
  await page.locator(`details:has(#${name})`).last().locator(':scope > summary').click();
  await expect(field).toBeVisible();
}

// serving waits for both listeners: /healthz says the process came up and got
// through OIDC discovery, and the shared socket poll confirms the SMTP port,
// which is bound on a goroutine of its own.
async function serving() {
  await expect(async () => {
    expect((await fetch(`${APPLIANCE}/healthz`)).ok).toBe(true);
    expect((await fetch(`${APPLIANCE}/setup`)).status).toBe(404);
  }).toPass({ intervals: [50], timeout: 30_000 });
  await pollSmtp({ smtpPort: SMTP_PORT, exited: false, log: 'Save and start did not open SMTP' });
}
